### PR TITLE
Expose consumption lag for tasks in AbstractKafkaConnector.

### PR DESCRIPTION
**Pull request by jzakaryan**
This pull request exposes the consumption lag info we have in AbstractKafkaConnector tasks.

Important: DO NOT REPORT SECURITY ISSUES DIRECTLY ON GITHUB.  
For reporting security issues and contributing security fixes,  
please, email security@linkedin.com instead, as described in  
the contribution guidelines.

Please, take a minute to review the contribution guidelines at:  
https://github.com/linkedin/Brooklin/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by vmaheshw — APPROVED** [review]
Can you please evaluate an open source knob as well, just like DATASTREAM_STATE, PARTITIONS, CONSUMER_OFFSET in AbstractKafkaConnector that can call this method and get the information?

**Review by somandal — APPROVED** [review]

**Comment by somandal** [comment]
> Can you please evaluate an open source knob as well, just like DATASTREAM_STATE, PARTITIONS, CONSUMER_OFFSET in AbstractKafkaConnector that can call this method and get the information?

I do believe this is already exposed via the CONSUMER_OFFSET diagnostics. @jzakaryan to confirm

**Comment by vmaheshw** [comment]
> > Can you please evaluate an open source knob as well, just like DATASTREAM_STATE, PARTITIONS, CONSUMER_OFFSET in AbstractKafkaConnector that can call this method and get the information?
> 
> I do believe this is already exposed via the CONSUMER_OFFSET diagnostics. @jzakaryan to confirm

Got it. Thanks. `CONSUMER_OFFSET` dumps for all the tasks in the host and this api will expose at task level.

**Comment by vmaheshw** [comment]
> > Can you please evaluate an open source knob as well, just like DATASTREAM_STATE, PARTITIONS, CONSUMER_OFFSET in AbstractKafkaConnector that can call this method and get the information?
> 
> I do believe this is already exposed via the CONSUMER_OFFSET diagnostics. @jzakaryan to confirm

Got it. Thanks. `Consumer_OFFSET` expose the information for all the tasks in the host, while this api will expose at task level.

**Pull request merged**
