### PR TITLE
Releasing Newer Version 5.4.3

### PR DESCRIPTION
**Pull request by shrinandthakkar**
Version Bump for Release
___
Important: DO NOT REPORT SECURITY ISSUES DIRECTLY ON GITHUB.  
For reporting security issues and contributing security fixes,  
please, email security@linkedin.com instead, as described in  
the contribution guidelines.

Please, take a minute to review the contribution guidelines at:  
https://github.com/linkedin/Brooklin/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by hshukla — APPROVED** [review]
:blessings:

**Review by ehoner — APPROVED** [review]

**Comment by 1arrow** [comment]
@shrinandthakkar can we also publish the relase artifacts here in github?

**Comment by shrinandthakkar** [comment]
> @shrinandthakkar can we also publish the relase artifacts here in github?

@1arrow ,sure will do.

**Comment by 1arrow** [comment]
Thanks, we have a similar issue in our production... occasionally brooklin is freezing. This could be a potential fix for us, please publish a release for this fix.

**Comment by shrinandthakkar** [comment]
> Thanks, we have a similar issue in our production... occasionally brooklin is freezing. This could be a potential fix for us, please publish a release for this fix.

Sure, released the latest version [5.4.3](https://github.com/linkedin/brooklin/releases/tag/5.4.3)

**Pull request merged**
